export enum EventType {
  AIRLINE_REGISTER_REQUEST,
  AIRLINE_REGISTER_FAIL,
  AIRLINE_REGISTER_SUCCESS,

  PASSENGER_REGISTER_REQUEST,
  PASSENGER_REGISTER_FAIL,
  PASSENGER_REGISTER_SUCCESS,

  TRIP_REGISTER_REQUEST,
  TRIP_REGISTER_FAIL,
  TRIP_REGISTER_SUCCESS,

  TRIP_SEAT_RESERVE_REQUEST,
  TRIP_SEAT_RESERVE_FAIL,
  TRIP_SEAT_RESERVE_SUCCESS,
}
