export enum EventType {
  AIRLINE_REGISTRATION_REQUEST,
  AIRLINE_REGISTRATION_REQUEST_FAILED,
  AIRLINE_REGISTRATION_REQUEST_SUCCEEDED,

  PASSENGER_REGISTRATION_REQUEST,
  PASSENGER_REGISTRATION_REQUEST_FAILED,
  PASSENGER_REGISTRATION_REQUEST_SUCCEEDED,

  TRIP_REGISTRATION_REQUEST,
  TRIP_REGISTRATION_REQUEST_FAILED,
  TRIP_REGISTRATION_REQUEST_SUCCEEDED,

  TRIP_SEAT_RESERVATION_REQUEST,
  TRIP_SEAT_RESERVATION_REQUEST_FAILED,
  TRIP_SEAT_RESERVATION_REQUEST_SUCCEEDED,
}
