const AIRLINE_SNAPSHOT: string = 'AIRLINE_SNAPSHOTS';

const PASSENGER_SNAPSHOT: string = 'PASSENGER_SNAPSHOTS';

const TRIP_SNAPSHOT: string = 'TRIP_SNAPSHOTS';

const AIRLINE: string = 'AIRLINES';

const EVENT_BUS: string = 'EVENT-BUS';

export const COLLECTIONS = {
  AIRLINE,
  AIRLINE_SNAPSHOT,
  PASSENGER_SNAPSHOT,
  TRIP_SNAPSHOT,
  EVENT_BUS,
};
